name: Reusable
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string    


jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "deploying"
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}